"""add enrichment ang generation fields

Revision ID: bff421a19e68
Revises: 7b23733aba24
Create Date: 2026-03-19 22:56:46.242297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff421a19e68'
down_revision: Union[str, Sequence[str], None] = '7b23733aba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_description_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_description_generations_product_id'), 'product_description_generations', ['product_id'], unique=False)
    op.add_column('orders', sa.Column('address_raw', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('postal_code', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('address_metadata', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('address_enrichment_status', sa.String(length=32), nullable=True))
    op.add_column('products', sa.Column('old_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('fur_type', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('length', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('size_range', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('material_composition', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('target_audience', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('season', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('style_tags', sa.JSON(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('email_raw', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_raw', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('contacts_enrichment_status', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'contacts_enrichment_status')
    op.drop_column('users', 'phone_raw')
    op.drop_column('users', 'email_raw')
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('products', 'style_tags')
    op.drop_column('products', 'season')
    op.drop_column('products', 'target_audience')
    op.drop_column('products', 'material_composition')
    op.drop_column('products', 'features')
    op.drop_column('products', 'size_range')
    op.drop_column('products', 'length')
    op.drop_column('products', 'color')
    op.drop_column('products', 'fur_type')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'old_description')
    op.drop_column('orders', 'address_enrichment_status')
    op.drop_column('orders', 'address_metadata')
    op.drop_column('orders', 'postal_code')
    op.drop_column('orders', 'address_raw')
    op.drop_index(op.f('ix_product_description_generations_product_id'), table_name='product_description_generations')
    op.drop_table('product_description_generations')
    # ### end Alembic commands ###
